---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - groupsync.primeroz.xyz
  resources:
  - httpsources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - groupsync.primeroz.xyz
  resources:
  - httpsources/finalizers
  verbs:
  - update
- apiGroups:
  - groupsync.primeroz.xyz
  resources:
  - httpsources/status
  verbs:
  - get
  - patch
  - update
